services:
  openai-api-gateway:
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: openai-api-gateway
    ports:
      - 8070:80
    env_file:
      - .env
    restart: unless-stopped
