services:
  azure-openai-api-gateway:
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: azure-openai-api-gateway
    ports:
      - 8071:80
    env_file:
      - .env-azure
    restart: unless-stopped
